# Generated by Django 5.2 on 2025-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
